# Generated by Django 4.0.1 on 2022-01-10 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_product_name_remove_product_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='category_gender_name')),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category_gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.categorygender', verbose_name='category_size'),
        ),
    ]
