# Generated by Django 4.0.1 on 2022-01-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_categoryprice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryprice',
            name='price',
            field=models.IntegerField(default=0, null=True, verbose_name='product_price'),
        ),
        migrations.AlterField(
            model_name='categoryprice',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='category_price_name'),
        ),
    ]
