# Generated by Django 4.0.1 on 2022-01-10 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_categoryprice_price_alter_categoryprice_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_color',
        ),
        migrations.DeleteModel(
            name='CategoryColor',
        ),
    ]
