# Generated by Django 4.0.1 on 2022-01-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_product_category_color_delete_categorycolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='category_color_name')),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
    ]
