# Generated by Django 4.0.1 on 2022-01-10 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_categorycolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.categorycolor', verbose_name='category_color'),
        ),
    ]
