# Generated by Django 4.0.1 on 2022-01-10 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_color',
        ),
        migrations.DeleteModel(
            name='CategoryColor',
        ),
    ]
