# Generated by Django 4.0.1 on 2022-01-10 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_remove_product_category_color_delete_categorycolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_gender',
        ),
        migrations.DeleteModel(
            name='CategoryGender',
        ),
    ]
