# Generated by Django 4.0.1 on 2022-01-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_remove_product_category_gender_delete_categorygender'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryclothes',
            name='need_in_set',
            field=models.IntegerField(default=0, null=True, verbose_name='weight_in_set'),
        ),
    ]
