# Generated by Django 4.0.1 on 2022-01-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_categoryclothes_need_in_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryclothes',
            name='need_in_set',
        ),
        migrations.AddField(
            model_name='categoryclothes',
            name='img',
            field=models.ImageField(null=True, upload_to='media/categories', verbose_name='img'),
        ),
    ]
