# Generated by Django 4.0.1 on 2022-01-23 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_remove_categoryclothes_need_in_set_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='category_image_name')),
                ('img', models.ImageField(null=True, upload_to='media/category_image', verbose_name='img')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.categoryimage', verbose_name='category_Image'),
        ),
    ]
