# Generated by Django 4.0.1 on 2022-01-29 09:24

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0015_categoryimage_product_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryclothes',
            name='img',
            field=models.ImageField(null=True, upload_to='media/category_image', verbose_name='img'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Название поста')),
                ('text', ckeditor.fields.RichTextField(null=True, verbose_name='Текст поста')),
                ('num', models.IntegerField(blank=True, default=0, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
