# Generated by Django 4.0.1 on 2022-01-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_remove_categoryimage_name_alter_categoryimage_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='img'),
        ),
    ]
