# Generated by Django 4.0.1 on 2022-02-10 19:18

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_remove_cartitem_ware_delete_cart_delete_cartitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('set_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('set_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Set',
                'verbose_name_plural': 'Sets',
            },
        ),
    ]
