# Generated by Django 4.0.1 on 2022-02-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_remove_set_set_product_set_set_product_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='set_product_1',
        ),
        migrations.AddField(
            model_name='set',
            name='pr',
            field=models.ManyToManyField(to='mainapp.Product'),
        ),
    ]
