# Generated by Django 4.0.2 on 2022-02-13 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_alter_categoryclothes_id_alter_categoryimage_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='pr',
        ),
        migrations.AddField(
            model_name='set',
            name='pr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.product'),
        ),
    ]
