# Generated by Django 4.0.2 on 2022-02-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_remove_set_pr_set_pr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='pr',
        ),
        migrations.AddField(
            model_name='set',
            name='pr',
            field=models.ManyToManyField(to='mainapp.Product'),
        ),
    ]
