# Generated by Django 4.0.2 on 2022-03-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_remove_set_pr_set_pr'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='media/docx', verbose_name='verify doc'),
        ),
    ]
