# Generated by Django 4.0.2 on 2022-03-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_post_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.CharField(max_length=50, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='post',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='phone'),
        ),
    ]
