# Generated by Django 4.0.2 on 2022-03-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_remove_post_title_post_email_post_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='phone',
            new_name='title',
        ),
    ]
